- hosts: all
  vars:
      - dir: lw
  tasks:
          - name: "Installing APACHE Webserver software"
            package:
                  name: "httpd"
                  state: present

          - name: "Installing the PHP software"
            package:
                  name: "php"
                  state: present
                  
          - name: " Creating a directory"
            file:
                  path: "/var/www/{{ dir }}"
                  
          - name: "Updating httpd config file"
            template:
                   dest: "/etc/httpd/conf.d/lw.conf"
                   src: "lw.conf"
            notify: webserver
        
          - name: "Starting the webserver"
            service:
                  name: "httpd"
                  state: started
         
          - name: "Copying the webpage to the webserver"
            copy:
                  dest: "/var/www/{{ dir }}/"
                  src: "/root/haproxy.php"
  handlers:
          - name: webserver
            service:
                    name: "httpd"
                    state: restarted 

          - name: "Starting firewall if not running"
            service:
                  name: "firewalld"
                  state: started
                  enabled: yes

          - name: "Creating firewall rule to expose the webserver on port no 80"
            firewalld:
                    port: "8080/tcp"
                    state: enabled
                    permanent: yes
                    immediate: yes







